sudo: required
services:
  - docker
  
before_install:
  - docker build -t arvindpant/docker-react -f Dockerfile.dev .
  
script:
  - docker run arvindpant/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-796378849469"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secrete_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"